create table tb_product (
  id bigint not null generated by default as identity
  (start with 1 increment by 1),
  name varchar(60) not null,
  description varchar(120) not null,
  value bigint not null,
  company_id bigint not null,
  created_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   
   primary key (id),
   
   constraint fk_company_product foreign key (company_id) references tb_company(id) 
);
