create table tb_order (
  id bigint not null generated by default as identity
  (start with 1 increment by 1),
  customer_id bigint not null,
  address_id bigint not null,
  created_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   
   primary key (id),
   
   constraint fk_customer_order foreign key (customer_id) references tb_customer(id),
   constraint fk_order_address foreign key (address_id) references tb_address(id) 

);
