create table tb_order_log (
  id bigint not null generated by default as identity
  (start with 1 increment by 1),
  status varchar(1) not null,
  description varchar(120) not null,
  order_id bigint not null,
  created_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
   
   primary key (id),
   
   constraint fk_order_log foreign key (order_id) references tb_order(id) 
);
